print(f'True and True:{True and True}')
print(f'True and False:{True and False}')
print(f'False and True:{False and True}')
print(f'True or True:{True or True}')
print(f'True or False:{True or False}')
print(f'False or False:{False or False}')
print(f'not True:{not True}')
print(f'not False:{not False}')