shoplist = ['apple', 'mango', 'carrot', 'banana']
index = shoplist.index('carrot')
print(index)
shoplist.insert(3, 'peach')
print(shoplist)
shoplist.insert(0, 'beef')
print(shoplist)
shoplist.append('beef')
print(shoplist)
shoplist.remove('beef')
print(shoplist)
shoplist.sort()
print(shoplist)
shoplist.sort(reverse=True)
print(shoplist)
shoplist.reverse()
print(shoplist)
print(len(shoplist))